#task_service_url: 'http://ec2-3-137-2-81.us-east-2.compute.amazonaws.com:5000/get-task'  #NOTE THIS IS FOR V1, for V2 we just use without the path.
orchestrator_url: "http://ec2-3-137-2-81.us-east-2.compute.amazonaws.com:5000"
api_token: 'YOUR_SECURE_API_TOKEN'
download_folder: './downloads'


