# config.yaml
orchestrator_url: "http://ec2-3-137-2-81.us-east-2.compute.amazonaws.com:5000"
download_folder: "./downloads"
api_token: "XXXXXXXXXMYAPITOKENHEREie134k123l4j23;46754772a42c9f5b5b772e5fbec1e93be09914c1f26b"  # The same token configured in the orchestrator


